version: '3.3'

services:
  adprovider:
    build: ./adprovider
    command: uvicorn adprovider-app.adprovider_main:app --reload --host 0.0.0.0 --port 8001
    volumes:
      - ./adprovider/:/app/
    ports:
      - 8001:8001
    environment:
      - DATABASE_URI=postgresql://postgres:password@recommender_db/recommender_database
      - CAST_SERVICE_HOST_URL=http://recommender_service:8000/api/v1/recommenders/


  recommender:
    build: ./recommender
    command: uvicorn recommender-app.recommender_main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./recommender/:/app/
    ports:
      - 8000:8000
    environment:
      - DATABASE_URI=postgresql://postgres:password@recommender_db/recommender_database

  recommender_db:
    image: postgres
    volumes:
      - postgres_data_recommender:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=recommender_db


volumes:
  postgres_data_adprovider:
  postgres_data_recommender: